<a href="https://colab.research.google.com/github/Sahithi530/Sahithi_INFO5731_Fall2024/blob/main/Tummala_Sahithi_Exercise_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **INFO5731 In-class Exercise 3**

The purpose of this exercise is to explore various aspects of text analysis, including feature extraction, feature selection, and text similarity ranking.

**Expectations**:
*   Use the provided .*ipynb* document to write your code & respond to the questions. Avoid generating a new file.
*   Write complete answers and run all the cells before submission.
*   Make sure the submission is "clean"; *i.e.*, no unnecessary code cells.
*   Once finished, allow shared rights from top right corner (*see Canvas for details*).

**Total points**: 40

**Deadline**: This in-class exercise is due at the end of Friday, at 11:59 PM.

**Late submissions will have a penalty of 10% of the marks for each day of late submission. , and no requests will be answered. Manage your time accordingly.**

**Please check that the link you submitted can be opened and points to the correct assignment.**

## Question 1 (10 Points)
Describe an interesting **text classification or text mining task** and explain what kind of features might be useful for you to build the machine learning model. List your features and explain why these features might be helpful. You need to list at least five different types of features. **Your dataset must be text.**

In [ ]:
# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):

'''
Actually, prioritization encompasses one of the biggest areas in effective customer service management, which is already a very important duty in text classification.
Of course, incoming emails can be categorized into different priority categories like Urgent, High, Medium, or Low automatically by the machine learning model itself.
Some of the key features will be Readability Metrics, Sentiment Analysis, Topic Modeling, Lexical Aspects, Customer Metadata, Named Entity Recognition, and Historical Data Features.
These lexical features encapsulate linguistic cues relevant to the urgency or importance of the issue while sentiment analysis aids in pre-ascertaining the overall sentiment score and the frequency of emotive terms.
While topic modeling gives the main topics using techniques such as Latent Dirichlet Allocation, for example, structural features give background information about the type and history of a given problem.
Examples of customer metadata include tier, account age, and past interaction history.

Lexical capabilities are factors of a textual content's vocabulary that can be used to measure the pleasant of a written piece, in particular instructional writing. Lexical capabilities can consist of:
Phrase duration: The period of words in a textual content
Phrase frequency: How regularly phrases appear in a text
Lexical density: The ratio of content phrases (nouns, verbs, adjectives, and adverbs) to the total variety of phrases in a text
Lexical range: The ratio of different words to the total variety of words in a text
Lexical sophistication: the proportion of excessive and coffee frequency phrases in a text
Lexical features may be greater goal than precise words because they may be measured from the textual content's angle, instead of from a predefined lexicon. This objectivity can help keep away from biases and limitations associated with predefined word lists.
A few not unusual lexical functions of instructional writing consist of:
Precision and technicality: academic writing regularly makes use of unique and technical vocabulary
Informational density: educational writing is regularly surprisingly based and incorporates a high percentage of nouns.


In reality! Consider a textual content type venture wherein we're building a machine studying version to categorize film critiques as high-quality or terrible. This is a common sentiment evaluation assignment, and the dataset could consist of text reviews from movie-goers or critics. Here are diverse forms of features we could use for this task:

1. Lexical capabilities:
   a) word frequency: count of unique phrases or phrases.
   B) N-grams: Sequences of 2-3 phrases that seem together.
   C) TF-IDF (term Frequency-Inverse record Frequency): degree of word significance.
   D) phrase period: average period of words used.

Why helpful: those capabilities seize the vocabulary utilized in critiques. Tremendous critiques might use phrases like "brilliant" or "pleasing" greater frequently, even as negative reviews might have greater words like "dull" or "disappointing".

2. Sentiment-based totally functions:
   a) overall sentiment rating: using pre-educated sentiment analyzers.
   B) Emotion phrases: Frequency of phrases related to exclusive feelings.
   C) Polarity scores: measure of the way fine or negative certain terms are.

Why beneficial: those immediately relate to the venture of figuring out whether a overview is positive or terrible. They capture the emotional tone of the text.

3. Syntactic functions:
   a) component-of-speech (POS) tags: Distribution of nouns, verbs, adjectives, and many others.
   B) Dependency parsing: Grammatical shape of sentences.
   C) Sentence period: average wide variety of words per sentence.

Why useful: The manner sentences are constructed can indicate sentiment. For instance, more adjectives is probably utilized in expressive, emotional critiques.

4. Stylometric features:
   a) Punctuation utilization: Frequency of exclamation marks, question marks, etc.
   B) Capitalization: Use of all-caps words (e.G., "high-quality" vs "top notch").
   C) clarity rankings: Measures like Flesch-Kincaid readability index.

Why useful: those capture writing fashion, which may be indicative of sentiment. Enthusiastic positive opinions may use extra exclamation factors, for example.

5. Subject matter-based functions:
   a) Latent Dirichlet Allocation (LDA) subjects: Distribution of summary "topics" within the text.
   B) film-particular key phrases: Presence of phrases associated to plan, performing, computer graphics, etc.

Why useful: unique elements of a movie (e.G., plot, appearing, visuals) is probably discussed more in tremendous or poor evaluations.


## Question 2 (10 Points)
Write python code to extract these features you discussed above. You can collect a few sample text data for the feature extraction.

In [ ]:
pip install --upgrade pip

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 6.3 MB/s eta 0:00:00a 0:00:01
  Attempting uninstall: pip
    Found existing installation: pip 24.0
    Uninstalling pip-24.0:
      Successfully uninstalled pip-24.0
Note: you may need to restart the kernel to use updated packages.


In [ ]:
pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.0/24.0 MB 48.7 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 30.4/30.4 MB 42.3 MB/s eta 0:00:00a 0:00:01
  Attempting uninstall: scipy
    Found existing installation: scipy 1.14.1
    Uninstalling scipy-1.14.1:
      Successfully uninstalled scipy-1.14.1
Note: you may need to restart the kernel to use updated packages.


In [ ]:
pip install spacy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import nltk
import spacy
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from nltk.sentiment import SentimentIntensityAnalyzer

# Download necessary NLTK data
nltk.download('vader_lexicon')
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

# Load spaCy model
nlp = spacy.load("en_core_web_sm")

sample_texts = [
    "I want to drink a coffee.",
    "I need help with an address.",
    "The dress is beautiful",
    "I'm having issues with this code",
    "Can you tell me how to go to this address?"
]

# Bag of Words
bow_vectorizer = CountVectorizer()
bow_features = bow_vectorizer.fit_transform(sample_texts)
print("Bag of Words (BoW) features:\n", bow_features.toarray())
print("BoW feature names:", bow_vectorizer.get_feature_names_out())

# TF-IDF
tfidf_vectorizer = TfidfVectorizer()
tfidf_features = tfidf_vectorizer.fit_transform(sample_texts)
print("\nTF-IDF features:\n", tfidf_features.toarray())
print("TF-IDF feature names:", tfidf_vectorizer.get_feature_names_out())

# N-grams
ngram_vectorizer = CountVectorizer(ngram_range=(2, 3))
ngram_features = ngram_vectorizer.fit_transform(sample_texts)
print("\nN-gram features (Bigrams/Trigrams):\n", ngram_features.toarray())
print("N-gram feature names:", ngram_vectorizer.get_feature_names_out())

# Sentiment Analysis
sentiment_analyzer = SentimentIntensityAnalyzer()
sentiment_scores = [sentiment_analyzer.polarity_scores(text) for text in sample_texts]
print("\nSentiment Scores:")
for text, score in zip(sample_texts, sentiment_scores):
    print(f"{text} --> {score}")

# Word Embeddings
print("\nWord Embeddings (SpaCy):")
for text in sample_texts:
    doc = nlp(text)
    print(f"Text: {text}")
    print(f"Embedding shape: {doc.vector.shape}")
    print(f"First 5 elements of embedding: {doc.vector[:5]}\n")

# Word Lengths
text_lengths = [len(nltk.word_tokenize(text)) for text in sample_texts]
print("\nLength of Text (in words):")
for text, length in zip(sample_texts, text_lengths):
    print(f"{text} --> {length} words")

# POS Tags
print("\nPart of Speech (POS) Tags:")
for text in sample_texts:
    doc = nlp(text)
    print(f"\nText: {text}")
    for token in doc:
        print(f"{token.text} ({token.pos_})", end=' ')
    print()


[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


Bag of Words (BoW) features:
 [[0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0]
 [1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 1 0]
 [1 0 0 1 0 0 0 0 1 0 0 1 0 0 1 0 1 0 1 2 0 0 1]]
BoW feature names: ['address' 'an' 'beautiful' 'can' 'code' 'coffee' 'dress' 'drink' 'go'
 'having' 'help' 'how' 'is' 'issues' 'me' 'need' 'tell' 'the' 'this' 'to'
 'want' 'with' 'you']

TF-IDF features:
 [[0.         0.         0.         0.         0.         0.52335825
  0.         0.52335825 0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.42224214 0.52335825 0.         0.        ]
 [0.38898761 0.48214012 0.         0.         0.         0.
  0.         0.         0.         0.         0.48214012 0.
  0.         0.         0.         0.48214012 0.         0.
  0.         0.         0.         0.38898761 0.        ]
 [0.         0.         0.5        

## Question 3 (10 points):
Use any of the feature selection methods mentioned in this paper "Deng, X., Li, Y., Weng, J., & Zhang, J. (2019). Feature selection for text classification: A review. Multimedia Tools & Applications, 78(3)."

Select the most important features you extracted above, rank the features based on their importance in the descending order.

In [3]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.feature_selection import chi2
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import LabelEncoder

#sampletext

texts = [
    "I want to share a feedback on a movie named Devara",
    "The delivery was late."
]
labels = ["Feedback", "Complaint"]

#Create a TF-IDF

vectorizer = TfidfVectorizer()

#Converting data
X = vectorizer.fit_transform(texts)

label_encoder = LabelEncoder()
y = label_encoder.fit_transform(labels)

# chi-squared feature selection

chi2_values, p_values = chi2(X, y)

feature_names = vectorizer.get_feature_names_out()
chi2_df = pd.DataFrame({'Feature': feature_names, 'Chi2': chi2_values})
chi2_df = chi2_df.sort_values(by='Chi2', ascending=False).reset_index(drop=True)

#printthefeature

print(chi2_df)


     Feature      Chi2
0   delivery  0.500000
1       late  0.500000
2        the  0.500000
3        was  0.500000
4     devara  0.353553
5   feedback  0.353553
6      movie  0.353553
7      named  0.353553
8         on  0.353553
9      share  0.353553
10        to  0.353553
11      want  0.353553


## Question 4 (10 points):
Write python code to rank the text based on text similarity. Based on the text data you used for question 2, design a query to match the most relevant docments. Please use the BERT model to represent both your query and the text data, then calculate the cosine similarity between the query and each text in your data. Rank the similary with descending order.

In [4]:
pip install transformers torch scikit-learn

In [ ]:
pip install transformers

  Using cached transformers-4.45.1-py3-none-any.whl.metadata (44 kB)
  Using cached huggingface_hub-0.25.1-py3-none-any.whl.metadata (13 kB)
  Using cached tokenizers-0.20.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (6.7 kB)
Using cached transformers-4.45.1-py3-none-any.whl (9.9 MB)
Using cached huggingface_hub-0.25.1-py3-none-any.whl (436 kB)
Using cached tokenizers-0.20.0-cp312-cp312-macosx_11_0_arm64.whl (2.5 MB)
Note: you may need to restart the kernel to use updated packages.


In [12]:


import torch
from transformers import BertTokenizer, BertModel
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

#SAMPLE text
sample_texts = [
    "I had the pleasant meal ever at that new eating place! Fantastically recommend it.",
    "The customer support changed into terrible. I will by no means shop right here again.",
    "I am considering buying a new computer. Any guidelines?",
    "I'm having issues with the billing."
]
#BERT embedding for a text
def get_bert_embedding(text, model, tokenizer):
    inputs = tokenizer(text, return_tensors='pt', truncation=True, padding=True)
    with torch.no_grad():
        outputs = model(**inputs)
    embeddings = outputs.last_hidden_state.mean(dim=1)
    return embeddings

#BERT embedding for all the text samples

text_embeddings = []
for text in sample_texts:
    text_embedding = get_bert_embedding(text, model, tokenizer)
    text_embeddings.append(text_embedding)

#concatinating

text_embeddings = torch.cat(text_embeddings)

query = "I am considering buying a new computer. Any guidelines?"

query_embedding = get_bert_embedding(query, model, tokenizer)

#sorting it in descending order

cosine_similarities = cosine_similarity(query_embedding, text_embeddings)[0]

ranked_indices = np.argsort(-cosine_similarities)

#print the query and ranked texts

print(f"Query: {query}\n")
print("Ranked Texts based on Similarity:")
for idx in ranked_indices:
    print(f"Text: {sample_texts[idx]} -- Similarity Score: {cosine_similarities[idx]:.4f}")



/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


Query: I am considering buying a new computer. Any guidelines?

Ranked Texts based on Similarity:
Text: I am considering buying a new computer. Any guidelines? -- Similarity Score: 1.0000
Text: I'm having issues with the billing. -- Similarity Score: 0.7383
Text: The customer support changed into terrible. I will by no means shop right here again. -- Similarity Score: 0.7074
Text: I had the pleasant meal ever at that new eating place! Fantastically recommend it. -- Similarity Score: 0.6892


# Mandatory Question

**Important: Reflective Feedback on this exercise**

Please provide your thoughts and feedback on the exercises you completed in this assignment. Consider the following points in your response:

Learning Experience: Describe your overall learning experience in working on extracting features from text data. What were the key concepts or techniques you found most beneficial in understanding the process?

Challenges Encountered: Were there specific difficulties in completing this exercise?

Relevance to Your Field of Study: How does this exercise relate to the field of NLP?

**(Your submission will not be graded if this question is left unanswered)**



In [ ]:



Engaging inside the procedure of extracting functions from textual information furnished a precious getting to know opportunity. I discovered that expertise standards like tokenization, stemming, and lemmatization is vital for transforming text records for analysis. The punkt library performed a essential function in coaching me the way to effectively dissect text into sentences and phrases. I found that tokenization no longer just enables with later processing like extracting functions and classifying, however is also important for comprehending the text's shape and that means.

Problems confronted

One of the principal obstacles I confronted turned into making sure that the vital libraries and resources, just like the punkt tokenizer, had been nicely hooked up and to be had in my Python setup. This required fixing issues with paths and permissions, which may be annoying, mainly whilst the library appeared to reveal that it was cutting-edge. The demanding situations in gaining access to punkt underscored the significance of environmental management in NLP tasks.

Significance for your vicinity of know-how

This challenge may be very essential within the location of natural Language Processing (NLP) as characteristic extraction is a critical a part of getting textual statistics ready for device gaining knowledge of models. Knowing a way to tokenize and preprocess text is vital for greater complex NLP activities like sentiment evaluation, named entity reputation, and topic modeling. The problems encountered with the punkt library highlighted the importance of having a sturdy draw close of programming and linguistic concepts while working with NLP gear. In standard, this come across highlighted the vital hyperlink among textual content processing techniques and their implementation in realistic NLP assignments.

